name: Build Windows Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          $assets_path = (python -c "import os, faster_whisper; print(os.path.join(os.path.dirname(faster_whisper.__file__), 'assets'))")
          pyinstaller --name "YouTubeDownloader" --onefile --console --add-data "$($assets_path);faster_whisper/assets" youtube_download.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # ✅ Fixed here (v3 → v4)
        with:
          name: youtube-downloader-win
          path: dist/YouTubeDownloader.exe
          retention-days: 7
